project_id: '521462'
api_token: 733c1ef577aeabc20f5e0c898f94cdc12b4120f8f5d6bdedda205f2f1c5c0fb5f840d521e3f35431
preserve_hierarchy: true
files:
  - source: /docs/**/*
    ignore:
      - /**/_category_.json
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
